### ISSUE TITLE
Issue with CLI

### ISSUE THREAD

**Issue by marutiprasad** [akamai/cli-purge#2]
Hi ,

I am getting the following issue, even though the .edgerc file is present with correct values.
```
./akamai-purge invalidate https://www.exmaple.com --staging
Purging...panic: Fatal missing required options: [host client_token client_secret access_token]

goroutine 1 [running]:
github.com/akamai/cli-purge/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid.InitEdgeRc(0x18a16700, 0xd, 0x18a16737, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid/config.go:109 +0x54e
github.com/akamai/cli-purge/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid.Init(0x18a16700, 0xd, 0x18a16727, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/edgegrid/config.go:49 +0x11c
main.purge(0x832f5a1, 0xa, 0x18a6a1e0, 0x829a02f, 0x18a6a1e0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/akamai-purge.go:157 +0x1a8
main.cmdInvalidate(0x18a6a1e0, 0x0, 0x18a6a1e0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/akamai-purge.go:131 +0x33
github.com/akamai/cli-purge/vendor/github.com/urfave/cli.HandleAction(0x82d8f60, 0x8343c40, 0x18a6a1e0, 0x18a5e300, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/vendor/github.com/urfave/cli/app.go:485 +0xa2
github.com/akamai/cli-purge/vendor/github.com/urfave/cli.Command.Run(0x832f5a1, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8331954, 0x12, 0x0, ...)
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/vendor/github.com/urfave/cli/command.go:193 +0x8ff
github.com/akamai/cli-purge/vendor/github.com/urfave/cli.(*App).Run(0x18a8a4e0, 0x18a0e120, 0x4, 0x4, 0x0, 0x0)
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/vendor/github.com/urfave/cli/app.go:250 +0x5ed
main.main()
	/Users/dshafik/src/go/src/github.com/akamai/cli-purge/akamai-purge.go:127 +0x5cc
```

could you please advise on the same.

**Comment by marutiprasad** [comment]
Added a [ccu] section in the edgerc file and the issue is gone. Thanks.

**Comment by dshafik** [comment]
@marutiprasad glad to see you've solved this issue, however the error is less than ideal! I'll add in some better error handling for the next release.

**Comment by marutiprasad** [comment]
Thanks, to be more clear (may be helpful to others)
if the CCU section is not defined in the .edgerc file and user is using the purge module then a message saying the" corrsponding ccu authorization user credentials are not found in the file"
This can be applied to other modules as well.
